// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSggZx7WwPyE6MrV5-K7NxSIQSXO4qMLI',
    appId: '1:706117446360:web:9e61a8c2c7f308ac75c5ad',
    messagingSenderId: '706117446360',
    projectId: 'chatapp-6211a',
    authDomain: 'chatapp-6211a.firebaseapp.com',
    storageBucket: 'chatapp-6211a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6Oscw6WLi6fZ0SaAz1NrhdRWA3nu1FAg',
    appId: '1:706117446360:android:21248d13c12291c275c5ad',
    messagingSenderId: '706117446360',
    projectId: 'chatapp-6211a',
    storageBucket: 'chatapp-6211a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_Zn344LUPvNBSwFenj3D82acNBqOaw94',
    appId: '1:706117446360:ios:6306c2cf00070d5a75c5ad',
    messagingSenderId: '706117446360',
    projectId: 'chatapp-6211a',
    storageBucket: 'chatapp-6211a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_Zn344LUPvNBSwFenj3D82acNBqOaw94',
    appId: '1:706117446360:ios:7055b152652c292b75c5ad',
    messagingSenderId: '706117446360',
    projectId: 'chatapp-6211a',
    storageBucket: 'chatapp-6211a.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
